dependencies:
- name: bad-build-3
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-gh-1550610389
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-1550610389
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: test2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
